# Load Files

In [1]:
from __future__ import absolute_import, division, print_function, unicode_literals

# Notebooks
import nbimporter
import os
import sys

module_path = os.path.abspath(os.path.join('..'))
if module_path not in sys.path:
    sys.path.append(module_path)

# Functions Notebook
from Utils import build_GAN, batch_build_GAN, corr_matrix
from Functions import holisticsTrainTest
from Functions import comfPMV, ppv, selectModelParameters, trainTest_tunedModel, buildTrainRF, buildTrainKNN
from Functions import buildTrainSVM, buildTrainNB, buildMLP, getClfMetrics, saveModel

# Pandas, matplotlib, pickle, seaborn
import pickle
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
# from collections import Counter

# Sklearn
from sklearn.manifold import TSNE
from sklearn import preprocessing

# Tensorflow
import tensorflow as tf

Importing Jupyter notebook from Utils.ipynb
Importing Jupyter notebook from GAN.ipynb
Importing Jupyter notebook from Functions.ipynb


In [2]:
# Run the pre-processing notebook first to make sure the pickle files exist

df_feature1 = pd.read_pickle("df_feature1.pkl")
# df_feature2 = pd.read_pickle("df_feature2.pkl")
# df_feature3 = pd.read_pickle("df_feature3.pkl")
# df_feature4 = pd.read_pickle("df_feature4.pkl")
# df_feature5 = pd.read_pickle("df_feature5.pkl")


In [3]:
test_size_percentage = 0.2 # for CV within train split
train_test_split = 0.8 # for main train/validation split

user_split = False #split train and test user-based or completely stratfied

use_heuristics_participants = False


In [4]:
df_aux_65 = pd.read_csv("../data/TCS_65_participants_outsideData.csv", delimiter = ",")

list_complete_participants = list(df_aux_65['Participant_No'].unique())

if use_heuristics_participants:
    list_complete_participants.append(10)
    list_complete_participants.append(26)
    list_complete_participants.append(28)
    list_complete_participants.append(36)
    list_complete_participants.append(37)
    list_complete_participants.append(39)
    list_complete_participants.append(47)
    list_complete_participants.append(48)
    list_complete_participants.append(53)

num_complete_participants = len(list_complete_participants)
print("Complete Participants: {}".format(list_complete_participants))
print("Total number of complete participants: {}".format(num_complete_participants))

Complete Participants: [1, 2, 4, 5, 6, 7, 8, 11, 12, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 27, 29, 30, 31, 32, 33, 34, 35, 40, 41, 42, 43, 44, 45, 46, 49, 50, 51, 52, 54, 55, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80]
Total number of complete participants: 65


In [20]:

df_feature1_train, df_feature1_test, df_feature1_train_binary, df_feature1_test_binary = holisticsTrainTest(df_feature1, 
                                                                                                            list_complete_participants,
                                                                                                            user_split = user_split,
                                                                                                            train_test_split = train_test_split)


# df_feature2_train, df_feature2_test, df_feature2_train_binary, df_feature2_test_binary  = holisticsTrainTest(df_feature2, 
#                                                                                                              list_complete_participants,
#                                                                                                             user_split = user_split,
#                                                                                                             train_test_split=train_test_split)

# df_feature3_train, df_feature3_test, df_feature3_train_binary, df_feature3_test_binary = holisticsTrainTest(df_feature3,
#                                                                                                            list_complete_participants,
#                                                                                                            user_split = user_split,
#                                                                                                            train_test_split=train_test_split)

# df_feature4_train, df_feature4_test, df_feature4_train_binary, df_feature4_test_binary = holisticsTrainTest(df_feature4,
#                                                                                                            list_complete_participants,
#                                                                                                            user_split = user_split,
#                                                                                                            train_test_split=train_test_split)

# df_feature5_train, df_feature5_test, df_feature5_train_binary, df_feature5_test_binary = holisticsTrainTest(df_feature5,
#                                                                                                             list_complete_participants,
#                                                                                                            user_split = user_split,
#                                                                                                            train_test_split=train_test_split)

print("Total number of instances: {}".format(df_feature1.shape[0]))
print(df_feature1['Discrete Thermal Comfort_TA'].value_counts())
print("Number of training instances: {}".format(df_feature1_train.shape[0]))
print("Number of testing (validation) instances: {}".format(df_feature1_test.shape[0]))

Total number of instances: 2067
 0    1152
-1     452
-2     217
 1     198
 2      48
Name: Discrete Thermal Comfort_TA, dtype: int64
Number of training instances: 1653
Number of testing (validation) instances: 414


# Preparing data

In [6]:
print(df_feature1_train['Discrete Thermal Comfort_TA'].value_counts())
print(df_feature1_test['Discrete Thermal Comfort_TA'].value_counts())
# df_feature1_train.to_csv('df_feature1_train.csv', index=False)

 0    918
-1    372
-2    173
 1    157
 2     33
Name: Discrete Thermal Comfort_TA, dtype: int64
 0    234
-1     80
-2     44
 1     41
 2     15
Name: Discrete Thermal Comfort_TA, dtype: int64


In [32]:
# needed datapoints per label
needed_0 = 950
needed_minus1 = 353 * 3
needed_minus2 = 190 * 3
needed_1 = 176 * 3
needed_2 = 44 * 3

print(needed_minus1)
print(needed_minus2)
print(needed_1)
print(needed_2)

1059
570
528
132


## Occutherm thermal comfort models

In [33]:
# load best models NB and KNN
acc_nb_1_train, nb_optimal_1 = buildTrainNB(df_feature1_train, test_size_percentage=test_size_percentage)
acc_knn_1_train, knn_optimal_1 = buildTrainKNN(df_feature1_train,test_size_percentage=test_size_percentage)
acc_svm_1_train, svm_optimal_1 = buildTrainSVM(df_feature1_train, test_size_percentage=test_size_percentage)

# using the optimal model. re-train in whole train split and test in unseen test split
acc_holistic_knn_1, _ = trainTest_tunedModel(df_feature1_test, knn_optimal_1)
acc_holistic_nb_1, _ = trainTest_tunedModel(df_feature1_test, nb_optimal_1)
acc_holistic_svm_1, _= trainTest_tunedModel(df_feature1_test, svm_optimal_1)

print(acc_holistic_knn_1)
print(acc_holistic_nb_1)
print(acc_holistic_svm_1)


Features: ['Temperature (Fahrenheit)' 'SkinTemperature' 'ClothingInsulation'
 'Height(cm)' 'Shoulder Circumference(cm)' 'Weight(lbs)' 'Gender'
 'Temperature_outside' 'Humidity_outside']
Expected accuracy (f1 micro) based on Cross-Validation:  0.5266228621517893
GaussianNB(priors=None, var_smoothing=1e-09)
Accuracy (f1 micro) on test set:  0.513595166163142
F1 micro on test set:  0.513595166163142
F1 macro on test set:  0.44454532230737226
Confusion Matrix: 
[[ 21   9   5   0   0]
 [ 19  28  27   0   0]
 [ 19  34 107  21   3]
 [  1   0  18  11   1]
 [  0   0   3   1   3]]
Classification Metrics: 
              precision    recall  f1-score   support

          -2       0.35      0.60      0.44        35
          -1       0.39      0.38      0.39        74
           0       0.67      0.58      0.62       184
           1       0.33      0.35      0.34        31
           2       0.43      0.43      0.43         7

   micro avg       0.51      0.51      0.51       331
   macro avg     

/home/matias/anaconda3/envs/tGAN/lib/python3.7/site-packages/sklearn/model_selection/_search.py:841: DeprecationWarning: The default of the `iid` parameter will change from True to False in version 0.22 and will be removed in 0.24. This will change numeric results when test-set sizes are unequal.
  DeprecationWarning)


Best parameters set found on development set:
{'algorithm': 'brute', 'metric': 'seuclidean', 'n_neighbors': 3, 'weights': 'distance'}
KNeighborsClassifier(algorithm='brute', leaf_size=30, metric='seuclidean',
           metric_params=None, n_jobs=None, n_neighbors=3, p=2,
           weights='distance')
Accuracy (f1 micro) on test set:  0.6858006042296072
F1 micro on test set:  0.6858006042296072
F1 macro on test set:  0.5602459224188084
Confusion Matrix: 
[[ 24   8   3   0   0]
 [ 12  38  24   0   0]
 [  3  26 147   7   1]
 [  0   0  11  16   4]
 [  0   0   1   4   2]]
Classification Metrics: 
              precision    recall  f1-score   support

          -2       0.62      0.69      0.65        35
          -1       0.53      0.51      0.52        74
           0       0.79      0.80      0.79       184
           1       0.59      0.52      0.55        31
           2       0.29      0.29      0.29         7

   micro avg       0.69      0.69      0.69       331
   macro avg       

/home/matias/anaconda3/envs/tGAN/lib/python3.7/site-packages/sklearn/model_selection/_search.py:841: DeprecationWarning: The default of the `iid` parameter will change from True to False in version 0.22 and will be removed in 0.24. This will change numeric results when test-set sizes are unequal.
  DeprecationWarning)


Best parameters set found on development set:
{'C': 1000, 'class_weight': 'balanced', 'gamma': 0.1, 'kernel': 'rbf'}
SVC(C=1000, cache_size=200, class_weight='balanced', coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma=0.1, kernel='rbf',
  max_iter=-1, probability=False, random_state=100, shrinking=True,
  tol=0.001, verbose=False)
Accuracy (f1 micro) on test set:  0.6827794561933535
F1 micro on test set:  0.6827794561933535
F1 macro on test set:  0.5749621346395539
Confusion Matrix: 
[[ 25  10   0   0   0]
 [ 11  47  15   1   0]
 [  6  35 134   8   1]
 [  1   2   7  18   3]
 [  0   0   1   4   2]]
Classification Metrics: 
              precision    recall  f1-score   support

          -2       0.58      0.71      0.64        35
          -1       0.50      0.64      0.56        74
           0       0.85      0.73      0.79       184
           1       0.58      0.58      0.58        31
           2       0.33      0.29      0.31         7

   micro avg       0.68      0.6

/home/matias/anaconda3/envs/tGAN/lib/python3.7/site-packages/sklearn/metrics/classification.py:1143: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
/home/matias/anaconda3/envs/tGAN/lib/python3.7/site-packages/sklearn/metrics/classification.py:1143: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
/home/matias/anaconda3/envs/tGAN/lib/python3.7/site-packages/sklearn/metrics/classification.py:1143: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
/home/matias/anaconda3/envs/tGAN/lib/python3.7/site-packages/sklearn/metrics/classification.py:1143: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted

# tGAN 

In [9]:
from tgan.model import TGANModel
# continuous_columns, that will contain a list with the indices of continuous columns.
# df_feature1_train.to_csv("../data/df_feature1_train.csv", index=False)
# print(df_feature1_train)
continuous_columns = [0, 1, 2, 3, 4, 5, 7, 8]


W0811 10:37:57.360398 139778422806336 module_wrapper.py:136] From /home/matias/anaconda3/envs/tGAN/lib/python3.7/site-packages/tensorflow_core/python/util/module_wrapper.py:163: The name tf.train.SessionRunHook is deprecated. Please use tf.estimator.SessionRunHook instead.



In [10]:
"""best architecture based on TGAN architecture search
{
"batch_size": 100, 
"z_dim": 100, 
"num_gen_rnn": 400, 
"num_gen_feature": 100, 
"num_dis_layers": 5, 
"num_dis_hidden": 200, 
"learning_rate": 0.0002, 
"noise": 0.1, 
"max_epoch": 5, 
"steps_per_epoch": 1000, 
"score": 0.5043731778425656
}
"""

'best architecture based on TGAN architecture search\n{\n"batch_size": 100, \n"z_dim": 100, \n"num_gen_rnn": 400, \n"num_gen_feature": 100, \n"num_dis_layers": 5, \n"num_dis_hidden": 200, \n"learning_rate": 0.0002, \n"noise": 0.1, \n"max_epoch": 5, \n"steps_per_epoch": 1000, \n"score": 0.5043731778425656\n}\n'

In [11]:
tgan = TGANModel(
    continuous_columns,
    output='output',
    max_epoch=5,
    steps_per_epoch=1000,
    save_checkpoints=True,
    restore_session=True,
    batch_size=100,
    z_dim=100,
    noise=0.1,
    learning_rate=0.0002,
    num_gen_rnn=400,
    num_gen_feature=100,
    num_dis_layers=5,
    num_dis_hidden=200,
    )

tgan.fit(df_feature1_train) # 

W0811 10:37:57.511141 139778422806336 module_wrapper.py:136] From /home/matias/anaconda3/envs/tGAN/lib/python3.7/site-packages/tensorflow_core/python/util/module_wrapper.py:163: The name tf.get_default_graph is deprecated. Please use tf.compat.v1.get_default_graph instead.



[0811 10:37:57 @input_source.py:222] Setting up the queue 'QueueInput/input_queue' for CPU prefetching ...


W0811 10:37:57.543535 139778422806336 module_wrapper.py:136] From /home/matias/anaconda3/envs/tGAN/lib/python3.7/site-packages/tensorflow_core/python/util/module_wrapper.py:163: The name tf.summary.scalar is deprecated. Please use tf.compat.v1.summary.scalar instead.

W0811 10:37:57.550619 139778422806336 deprecation.py:323] From /home/matias/anaconda3/envs/tGAN/lib/python3.7/site-packages/tgan/model.py:259: LSTMCell.__init__ (from tensorflow.python.ops.rnn_cell_impl) is deprecated and will be removed in a future version.
Instructions for updating:
This class is equivalent as tf.keras.layers.LSTMCell, and will be replaced by that in Tensorflow 2.0.
W0811 10:37:57.572559 139778422806336 deprecation.py:323] From /home/matias/anaconda3/envs/tGAN/lib/python3.7/site-packages/tensorflow_core/python/ops/rnn_cell_impl.py:957: Layer.add_variable (from tensorflow.python.keras.engine.base_layer) is deprecated and will be removed in a future version.
Instructions for updating:
Please use `layer.ad

[0811 10:37:57 @registry.py:126] gen/LSTM/00/FC input: [100, 400]


W0811 10:37:57.597186 139778422806336 module_wrapper.py:136] From /home/matias/anaconda3/envs/tGAN/lib/python3.7/site-packages/tensorflow_core/python/util/module_wrapper.py:163: The name tf.layers.Dense is deprecated. Please use tf.compat.v1.layers.Dense instead.

W0811 10:37:57.597885 139778422806336 deprecation.py:323] From /home/matias/anaconda3/envs/tGAN/lib/python3.7/site-packages/tensorpack/models/fc.py:67: Layer.apply (from tensorflow.python.keras.engine.base_layer) is deprecated and will be removed in a future version.
Instructions for updating:
Please use `layer.__call__` method instead.


[0811 10:37:57 @registry.py:134] gen/LSTM/00/FC output: [100, 100]
[0811 10:37:57 @registry.py:126] gen/LSTM/00/FC2 input: [100, 100]
[0811 10:37:57 @registry.py:134] gen/LSTM/00/FC2 output: [100, 1]
[0811 10:37:57 @registry.py:126] gen/LSTM/01/FC input: [100, 400]
[0811 10:37:57 @registry.py:134] gen/LSTM/01/FC output: [100, 100]
[0811 10:37:57 @registry.py:126] gen/LSTM/01/FC2 input: [100, 100]
[0811 10:37:57 @registry.py:134] gen/LSTM/01/FC2 output: [100, 5]
[0811 10:37:57 @registry.py:126] gen/LSTM/01/FC3 input: [100, 5]
[0811 10:37:57 @registry.py:134] gen/LSTM/01/FC3 output: [100, 100]
[0811 10:37:57 @registry.py:126] gen/LSTM/02/FC input: [100, 400]
[0811 10:37:57 @registry.py:134] gen/LSTM/02/FC output: [100, 100]
[0811 10:37:57 @registry.py:126] gen/LSTM/02/FC2 input: [100, 100]
[0811 10:37:57 @registry.py:134] gen/LSTM/02/FC2 output: [100, 1]
[0811 10:37:57 @registry.py:126] gen/LSTM/03/FC input: [100, 400]
[0811 10:37:57 @registry.py:134] gen/LSTM/03/FC output: [100, 100]
[0

[0811 10:37:59 @registry.py:126] discrim/dis_fc4/fc input: [100, 210]
[0811 10:37:59 @registry.py:134] discrim/dis_fc4/fc output: [100, 200]
[0811 10:37:59 @registry.py:126] discrim/dis_fc4/fc_diversity input: [100, 200]
[0811 10:37:59 @registry.py:134] discrim/dis_fc4/fc_diversity output: [100, 100]
[0811 10:37:59 @registry.py:126] discrim/dis_fc_top input: [100, 210]
[0811 10:37:59 @registry.py:134] discrim/dis_fc_top output: [100, 1]


W0811 10:37:59.719285 139778422806336 deprecation.py:323] From /home/matias/anaconda3/envs/tGAN/lib/python3.7/site-packages/tensorflow_core/python/ops/nn_impl.py:183: where (from tensorflow.python.ops.array_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where
W0811 10:37:59.740694 139778422806336 lazy_loader.py:50] 
The TensorFlow contrib module will not be included in TensorFlow 2.0.
For more information, please see:
  * https://github.com/tensorflow/community/blob/master/rfcs/20180907-contrib-sunset.md
  * https://github.com/tensorflow/addons
  * https://github.com/tensorflow/io (for I/O related ops)
If you depend on functionality not listed there, please file an issue.



[0811 10:38:06 @logger.py:90] Argv: /home/matias/anaconda3/envs/tGAN/lib/python3.7/site-packages/ipykernel_launcher.py -f /run/user/1000/jupyter/kernel-cf0327a3-c69f-4ffd-bf91-0d4982bee916.json


W0811 10:38:06.255463 139778422806336 module_wrapper.py:136] From /home/matias/anaconda3/envs/tGAN/lib/python3.7/site-packages/tensorflow_core/python/util/module_wrapper.py:163: The name tf.gfile.IsDirectory is deprecated. Please use tf.io.gfile.isdir instead.



[0811 10:38:06 @model_utils.py:67] List of Trainable Variables: 
name                              shape           #elements
--------------------------------  ------------  -----------
gen/LSTM/go:0                     [1, 100]              100
gen/LSTM/lstm_cell/kernel:0       [1000, 1600]      1600000
gen/LSTM/lstm_cell/bias:0         [1600]               1600
gen/LSTM/00/FC/W:0                [400, 100]          40000
gen/LSTM/00/FC/b:0                [100]                 100
gen/LSTM/00/FC2/W:0               [100, 1]              100
gen/LSTM/00/FC2/b:0               [1]                     1
gen/LSTM/00/attw:0                [1, 1, 1]               1
gen/LSTM/01/FC/W:0                [400, 100]          40000
gen/LSTM/01/FC/b:0                [100]                 100
gen/LSTM/01/FC2/W:0               [100, 5]              500
gen/LSTM/01/FC2/b:0               [5]                     5
gen/LSTM/01/FC3/W:0               [5, 100]              500
gen/LSTM/01/FC3/b:0               [

[0811 10:38:06 @base.py:209] Setup callbacks graph ...
[0811 10:38:06 @summary.py:46] [MovingAverageSummary] 6 operations in collection 'MOVING_SUMMARY_OPS' will be run with session hooks.
[0811 10:38:06 @summary.py:93] Summarizing collection 'summaries' of size 9.
[0811 10:38:06 @graph.py:98] Applying collection UPDATE_OPS of 20 ops.
[0811 10:38:07 @base.py:230] Creating the session ...


W0811 10:38:07.844897 139778422806336 deprecation.py:323] From /home/matias/anaconda3/envs/tGAN/lib/python3.7/site-packages/tensorpack/tfutils/sesscreate.py:62: get_backward_walk_ops (from tensorflow.contrib.graph_editor.select) is deprecated and will be removed after 2019-06-06.
Instructions for updating:
Please use tensorflow.python.ops.op_selector.get_backward_walk_ops.


[0811 10:38:09 @base.py:236] Initializing the session ...
[0811 10:38:09 @base.py:243] Graph Finalized.
[0811 10:38:10 @concurrency.py:38] Starting EnqueueThread QueueInput/input_queue ...
[0811 10:38:10 @base.py:275] Start Epoch 1 ...


100%|##########|1000/1000[07:00<00:00, 2.38it/s]

[0811 10:45:11 @base.py:285] Epoch 1 (global_step 1000) finished, time:7 minutes.


[0811 10:45:11 @saver.py:79] Model saved to output/model/model-1000.
[0811 10:45:11 @monitor.py:467] GAN_loss/discrim/accuracy_fake: 0.83
[0811 10:45:11 @monitor.py:467] GAN_loss/discrim/accuracy_real: 0.14
[0811 10:45:11 @monitor.py:467] GAN_loss/discrim/loss: 0.68736
[0811 10:45:11 @monitor.py:467] GAN_loss/gen/final-g-loss: 1.0303
[0811 10:45:11 @monitor.py:467] GAN_loss/gen/klloss: 0.076447
[0811 10:45:11 @monitor.py:467] GAN_loss/gen/loss: 0.95384
[0811 10:45:11 @monitor.py:467] QueueInput/queue_size: 50
[0811 10:45:11 @base.py:275] Start Epoch 2 ...


100%|##########|1000/1000[06:52<00:00, 2.43it/s]

[0811 10:52:03 @base.py:285] Epoch 2 (global_step 2000) finished, time:6 minutes 52 seconds.
[0811 10:52:04 @saver.py:79] Model saved to output/model/model-2000.
[0811 10:52:04 @monitor.py:467] GAN_loss/discrim/accuracy_fake: 0.94
[0811 10:52:04 @monitor.py:467] GAN_loss/discrim/accuracy_real: 0.04
[0811 10:52:04 @monitor.py:467] GAN_loss/discrim/loss: 0.67641
[0811 10:52:04 @monitor.py:467] GAN_loss/gen/final-g-loss: 1.0694
[0811 10:52:04 @monitor.py:467] GAN_loss/gen/klloss: 0.15584
[0811 10:52:04 @monitor.py:467] GAN_loss/gen/loss: 0.91359
[0811 10:52:04 @monitor.py:467] QueueInput/queue_size: 50
[0811 10:52:04 @base.py:275] Start Epoch 3 ...



100%|##########|1000/1000[06:52<00:00, 2.42it/s]

[0811 10:58:56 @base.py:285] Epoch 3 (global_step 3000) finished, time:6 minutes 52 seconds.
[0811 10:58:56 @saver.py:79] Model saved to output/model/model-3000.
[0811 10:58:56 @monitor.py:467] GAN_loss/discrim/accuracy_fake: 1
[0811 10:58:56 @monitor.py:467] GAN_loss/discrim/accuracy_real: 0
[0811 10:58:56 @monitor.py:467] GAN_loss/discrim/loss: 0.66683
[0811 10:58:56 @monitor.py:467] GAN_loss/gen/final-g-loss: 1.0455
[0811 10:58:56 @monitor.py:467] GAN_loss/gen/klloss: 0.13362
[0811 10:58:56 @monitor.py:467] GAN_loss/gen/loss: 0.9119
[0811 10:58:56 @monitor.py:467] QueueInput/queue_size: 50
[0811 10:58:56 @base.py:275] Start Epoch 4 ...



100%|##########|1000/1000[06:52<00:00, 2.43it/s]

[0811 11:05:48 @base.py:285] Epoch 4 (global_step 4000) finished, time:6 minutes 52 seconds.
[0811 11:05:48 @saver.py:79] Model saved to output/model/model-4000.
[0811 11:05:48 @monitor.py:467] GAN_loss/discrim/accuracy_fake: 1
[0811 11:05:48 @monitor.py:467] GAN_loss/discrim/accuracy_real: 0
[0811 11:05:48 @monitor.py:467] GAN_loss/discrim/loss: 0.67072
[0811 11:05:48 @monitor.py:467] GAN_loss/gen/final-g-loss: 1.1488
[0811 11:05:48 @monitor.py:467] GAN_loss/gen/klloss: 0.23303
[0811 11:05:48 @monitor.py:467] GAN_loss/gen/loss: 0.91579
[0811 11:05:48 @monitor.py:467] QueueInput/queue_size: 50
[0811 11:05:48 @base.py:275] Start Epoch 5 ...



100%|##########|1000/1000[06:52<00:00, 2.43it/s]

[0811 11:12:40 @base.py:285] Epoch 5 (global_step 5000) finished, time:6 minutes 52 seconds.
[0811 11:12:40 @saver.py:79] Model saved to output/model/model-5000.
[0811 11:12:40 @monitor.py:467] GAN_loss/discrim/accuracy_fake: 1
[0811 11:12:40 @monitor.py:467] GAN_loss/discrim/accuracy_real: 0
[0811 11:12:40 @monitor.py:467] GAN_loss/discrim/loss: 0.67062
[0811 11:12:40 @monitor.py:467] GAN_loss/gen/final-g-loss: 1.0985
[0811 11:12:40 @monitor.py:467] GAN_loss/gen/klloss: 0.18
[0811 11:12:40 @monitor.py:467] GAN_loss/gen/loss: 0.91853
[0811 11:12:40 @monitor.py:467] QueueInput/queue_size: 50
[0811 11:12:40 @base.py:289] Training has finished!


[0811 11:12:40 @input_source.py:178] EnqueueThread QueueInput/input_queue Exited.
[0811 11:12:42 @collection.py:146] New collections created in tower : tf.GraphKeys.REGULARIZATION_LOSSES
[0811 11:12:42 @collection.py:165] These collections were modified but restored in : (tf.GraphKeys.SUMMARIES: 0->2)
[0811 11:12:42 @sessinit.py:87] WRN The following variables are in the checkpoint, but not found in the graph: global_step, optimize/beta1_power, optimize/beta2_power
[0811 11:12:43 @sessinit.py:114] Restoring checkpoint from output/model/model-5000 ...


## Generate samples

In [12]:
def sample_needed_label(num_samples, label):
    synth_df = pd.DataFrame(columns=df_feature1.columns.values[1:])
    count = 0
    finish_loop = False
    # generate as many sampels of label 0 as needed
    while True:
        if finish_loop:
            break

        # sample a bunch of points
        curr_df = tgan.sample(1000)
        # iterate through all
        for index, row in curr_df.iterrows():
            if row['Discrete Thermal Comfort_TA'] == label:
                synth_df = synth_df.append(row)
                count += 1
                print(count)
                if count == num_samples:
                    finish_loop = True
                    break
    return synth_df


In [13]:
print("Samples needed: {}".format(needed_0))
synth_0 = sample_needed_label(needed_0, '0')


  0%|          |0/100[00:00<?,?it/s]

Samples needed: 950


  9%|9         |9/100[00:01<00:13, 6.86it/s]


1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119
120
121
122
123
124
125
126
127
128
129
130
131
132
133
134
135
136
137
138
139
140
141
142
143
144
145
146
147
148
149
150
151
152
153
154
155
156
157
158
159
160
161
162
163
164
165
166
167
168
169
170
171
172
173
174
175
176
177
178
179
180
181
182
183
184
185
186
187
188
189
190
191
192
193
194
195
196
197
198
199
200
201
202
203
204
205
206
207
208
209
210
211
212
213
214
215
216
217
218
219
220
221
222
223
224
225
226
227
228
229
230
231
232
233
234
235
236
237
238
239
240
241
242
243
244
245
246
247
248
249
250
251
252
253
254
255
256
257
258
259
260
261
262
263
264
265
266
267
268
269
270
271
272
273
274
275
276
277


In [34]:
print("Samples needed: {}".format(needed_minus1))
synth_minus1 = sample_needed_label(needed_minus1, '-1')

  0%|          |0/100[00:00<?,?it/s]

Samples needed: 1059


  0%|          |0/100[00:00<?,?it/s]

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31


  0%|          |0/100[00:00<?,?it/s]

32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66


  0%|          |0/100[00:00<?,?it/s]

67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94


  0%|          |0/100[00:00<?,?it/s]

95
96
97
98
99
100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119
120
121
122
123
124
125
126


  0%|          |0/100[00:00<?,?it/s]

127
128
129
130
131
132
133
134
135
136
137
138
139
140
141
142
143
144
145
146
147
148
149
150
151
152
153
154
155
156
157


  0%|          |0/100[00:00<?,?it/s]

158
159
160
161
162
163
164
165
166
167
168
169
170
171
172
173
174
175
176
177
178
179
180
181
182
183
184
185
186
187
188
189
190
191


  0%|          |0/100[00:00<?,?it/s]

192
193
194
195
196
197
198
199
200
201
202
203
204
205
206
207
208
209
210
211
212
213
214
215


  0%|          |0/100[00:00<?,?it/s]

216
217
218
219
220
221
222
223
224
225
226
227
228
229
230
231
232
233
234
235
236
237
238
239
240
241
242
243
244
245
246
247
248


  0%|          |0/100[00:00<?,?it/s]

249
250
251
252
253
254
255
256
257
258
259
260
261
262
263
264
265
266
267
268
269
270
271
272
273
274
275
276
277
278
279
280
281
282


  0%|          |0/100[00:00<?,?it/s]

283
284
285
286
287
288
289
290
291
292
293
294
295
296
297
298
299
300
301
302
303
304
305
306
307
308
309
310
311
312
313
314
315
316
317
318
319
320


  0%|          |0/100[00:00<?,?it/s]

321
322
323
324
325
326
327
328
329
330
331
332
333
334
335
336
337
338
339
340
341
342
343
344
345
346
347
348
349
350
351
352
353
354


  0%|          |0/100[00:00<?,?it/s]

355
356
357
358
359
360
361
362
363
364
365
366
367
368
369
370
371
372
373


  9%|9         |9/100[00:01<00:10, 8.90it/s]


374
375
376
377
378
379
380
381
382
383
384
385
386
387
388
389
390
391
392
393
394
395
396
397
398
399
400
401
402
403
404
405
406
407
408
409
410
411
412
413
414
415
416


  0%|          |0/100[00:00<?,?it/s]

417
418
419
420
421
422
423
424
425
426
427
428
429
430
431
432
433
434
435
436
437
438
439
440


  0%|          |0/100[00:00<?,?it/s]

441
442
443
444
445
446
447
448
449
450
451
452
453
454
455
456
457
458
459
460
461
462
463
464
465
466
467
468
469
470
471
472
473
474
475
476


  0%|          |0/100[00:00<?,?it/s]

477
478
479
480
481
482
483
484
485
486
487
488
489
490
491
492
493
494
495
496
497
498
499
500
501
502
503


  9%|9         |9/100[00:01<00:10, 8.87it/s]


504
505
506
507
508
509
510
511
512
513
514
515
516
517
518
519
520
521
522
523
524
525
526
527
528
529
530
531
532
533
534
535
536
537
538
539
540
541
542
543
544
545


  0%|          |0/100[00:00<?,?it/s]

546
547
548
549
550
551
552
553
554
555
556
557
558
559
560
561
562
563
564


  0%|          |0/100[00:00<?,?it/s]

565
566
567
568
569
570
571
572
573
574
575
576
577
578
579
580
581
582
583
584
585
586
587
588
589
590
591
592
593
594


  0%|          |0/100[00:00<?,?it/s]

595
596
597
598
599
600
601
602
603
604
605
606
607
608
609
610
611
612
613
614
615
616
617
618
619
620
621
622
623
624
625


  0%|          |0/100[00:00<?,?it/s]

626
627
628
629
630
631
632
633
634
635
636
637
638
639
640
641
642
643
644
645
646
647
648
649
650
651
652
653
654
655
656


  0%|          |0/100[00:00<?,?it/s]

657
658
659
660
661
662
663
664
665
666
667
668
669
670
671
672
673
674
675
676
677
678
679
680
681
682
683
684
685
686
687
688


  0%|          |0/100[00:00<?,?it/s]

689
690
691
692
693
694
695
696
697
698
699
700
701
702
703
704
705
706
707
708
709
710
711


  0%|          |0/100[00:00<?,?it/s]

712
713
714
715
716
717
718
719
720
721
722
723
724
725
726
727
728
729
730
731
732
733
734
735
736
737
738


  0%|          |0/100[00:00<?,?it/s]

739
740
741
742
743
744
745
746
747
748
749
750
751
752
753
754


  0%|          |0/100[00:00<?,?it/s]

755
756
757
758
759
760
761
762
763
764
765
766
767
768
769
770
771
772
773
774
775
776
777
778
779
780
781
782
783
784
785
786
787
788
789
790
791


  0%|          |0/100[00:00<?,?it/s]

792
793
794
795
796
797
798
799
800
801
802
803
804
805
806
807
808
809
810
811
812
813
814
815
816
817
818
819


  0%|          |0/100[00:00<?,?it/s]

820
821
822
823
824
825
826
827
828
829
830
831
832
833
834
835
836
837
838
839
840
841
842
843
844
845
846
847
848
849
850
851
852
853
854
855
856
857
858
859


  9%|9         |9/100[00:01<00:10, 8.93it/s]


860
861
862
863
864
865
866
867
868
869
870
871
872
873
874
875
876
877
878
879
880
881
882
883
884
885
886
887
888
889
890
891
892
893
894
895
896
897
898
899
900
901
902


  0%|          |0/100[00:00<?,?it/s]

903
904


  0%|          |0/100[00:00<?,?it/s]

905
906
907
908
909
910
911
912
913
914
915
916
917
918
919
920
921
922
923
924
925
926
927
928
929
930
931
932
933
934
935
936
937
938


  0%|          |0/100[00:00<?,?it/s]

939
940
941
942
943
944
945
946
947
948
949
950
951
952
953
954
955
956
957
958
959
960
961
962
963
964
965
966
967
968
969


  0%|          |0/100[00:00<?,?it/s]

970
971
972
973
974
975
976
977
978
979
980
981
982
983
984
985
986
987
988
989
990
991
992
993
994
995
996
997
998
999
1000
1001
1002
1003


  9%|9         |9/100[00:01<00:10, 8.90it/s]


1004
1005
1006
1007
1008
1009
1010
1011
1012
1013
1014
1015
1016
1017
1018
1019
1020
1021
1022
1023
1024
1025
1026
1027
1028
1029
1030
1031
1032
1033
1034
1035
1036
1037
1038
1039
1040
1041
1042
1043
1044
1045
1046


  0%|          |0/100[00:00<?,?it/s]

1047
1048
1049
1050
1051


  9%|9         |9/100[00:01<00:10, 8.91it/s]

1052
1053
1054
1055
1056
1057
1058
1059


In [ ]:
print("Samples needed: {}".format(needed_minus2))
synth_minus2 = sample_needed_label(needed_minus2, '-2')

  0%|          |0/100[00:00<?,?it/s]

Samples needed: 570


  0%|          |0/100[00:00<?,?it/s]

1


  0%|          |0/100[00:00<?,?it/s]

2
3


  0%|          |0/100[00:00<?,?it/s]

4


  0%|          |0/100[00:00<?,?it/s]

5


  0%|          |0/100[00:00<?,?it/s]

6


  0%|          |0/100[00:00<?,?it/s]

7


  0%|          |0/100[00:00<?,?it/s]

8


  0%|          |0/100[00:00<?,?it/s]

9
10


  0%|          |0/100[00:00<?,?it/s]

11


  0%|          |0/100[00:00<?,?it/s]

12


  0%|          |0/100[00:00<?,?it/s]

13


  0%|          |0/100[00:00<?,?it/s]

14


  0%|          |0/100[00:00<?,?it/s]

15


  0%|          |0/100[00:00<?,?it/s]

16
17


  0%|          |0/100[00:00<?,?it/s]

18


  0%|          |0/100[00:00<?,?it/s]

19
20


  0%|          |0/100[00:00<?,?it/s]

21


  0%|          |0/100[00:00<?,?it/s]

22


  0%|          |0/100[00:00<?,?it/s]

23


  0%|          |0/100[00:00<?,?it/s]

24


  0%|          |0/100[00:00<?,?it/s]

25


  0%|          |0/100[00:00<?,?it/s]

26


  0%|          |0/100[00:00<?,?it/s]

27
28


  0%|          |0/100[00:00<?,?it/s]

29


  0%|          |0/100[00:00<?,?it/s]

30


  0%|          |0/100[00:00<?,?it/s]

31


  0%|          |0/100[00:00<?,?it/s]

32


  0%|          |0/100[00:00<?,?it/s]

33


  0%|          |0/100[00:00<?,?it/s]

34


  0%|          |0/100[00:00<?,?it/s]

35


  0%|          |0/100[00:00<?,?it/s]

36


  0%|          |0/100[00:00<?,?it/s]

37


  0%|          |0/100[00:00<?,?it/s]

38
39


  0%|          |0/100[00:00<?,?it/s]

40


  0%|          |0/100[00:00<?,?it/s]

41


  0%|          |0/100[00:00<?,?it/s]

42


  0%|          |0/100[00:00<?,?it/s]

43


  0%|          |0/100[00:00<?,?it/s]

44


  0%|          |0/100[00:00<?,?it/s]

45


  0%|          |0/100[00:00<?,?it/s]

46


  0%|          |0/100[00:00<?,?it/s]

47


  0%|          |0/100[00:00<?,?it/s]

48


  0%|          |0/100[00:00<?,?it/s]

49


  0%|          |0/100[00:00<?,?it/s]

50
51


  0%|          |0/100[00:00<?,?it/s]

52


  0%|          |0/100[00:00<?,?it/s]

53


  0%|          |0/100[00:00<?,?it/s]

54


  0%|          |0/100[00:00<?,?it/s]

55


  0%|          |0/100[00:00<?,?it/s]

56


  0%|          |0/100[00:00<?,?it/s]

57


  0%|          |0/100[00:00<?,?it/s]

58


  0%|          |0/100[00:00<?,?it/s]

59
60


  0%|          |0/100[00:00<?,?it/s]

61
62


  0%|          |0/100[00:00<?,?it/s]

63


  0%|          |0/100[00:00<?,?it/s]

64


  0%|          |0/100[00:00<?,?it/s]

65


  0%|          |0/100[00:00<?,?it/s]

66


  0%|          |0/100[00:00<?,?it/s]

67


  0%|          |0/100[00:00<?,?it/s]

68


  0%|          |0/100[00:00<?,?it/s]

69


  0%|          |0/100[00:00<?,?it/s]

70


  0%|          |0/100[00:00<?,?it/s]

71


  0%|          |0/100[00:00<?,?it/s]

72


  0%|          |0/100[00:00<?,?it/s]

73


  0%|          |0/100[00:00<?,?it/s]

74
75


  0%|          |0/100[00:00<?,?it/s]

76


  0%|          |0/100[00:00<?,?it/s]

77


  0%|          |0/100[00:00<?,?it/s]

78


  0%|          |0/100[00:00<?,?it/s]

79


  0%|          |0/100[00:00<?,?it/s]

80


  0%|          |0/100[00:00<?,?it/s]

81
82


  0%|          |0/100[00:00<?,?it/s]

83
84


  0%|          |0/100[00:00<?,?it/s]

85
86


  0%|          |0/100[00:00<?,?it/s]

87


  0%|          |0/100[00:00<?,?it/s]

88


  0%|          |0/100[00:00<?,?it/s]

89


  0%|          |0/100[00:00<?,?it/s]

90


  0%|          |0/100[00:00<?,?it/s]

91


  0%|          |0/100[00:00<?,?it/s]

92


  0%|          |0/100[00:00<?,?it/s]

93
94


  0%|          |0/100[00:00<?,?it/s]

95
96


  0%|          |0/100[00:00<?,?it/s]

97
98


  0%|          |0/100[00:00<?,?it/s]

99


  0%|          |0/100[00:00<?,?it/s]

100
101


  0%|          |0/100[00:00<?,?it/s]

102


  0%|          |0/100[00:00<?,?it/s]

103
104


  0%|          |0/100[00:00<?,?it/s]

105


  0%|          |0/100[00:00<?,?it/s]

106


  0%|          |0/100[00:00<?,?it/s]

107


  0%|          |0/100[00:00<?,?it/s]

108


  0%|          |0/100[00:00<?,?it/s]

109


  0%|          |0/100[00:00<?,?it/s]

110


  0%|          |0/100[00:00<?,?it/s]

111


  0%|          |0/100[00:00<?,?it/s]

112


  0%|          |0/100[00:00<?,?it/s]

113


  0%|          |0/100[00:00<?,?it/s]

114


  0%|          |0/100[00:00<?,?it/s]

115


  0%|          |0/100[00:00<?,?it/s]

116
117


  0%|          |0/100[00:00<?,?it/s]

118


  0%|          |0/100[00:00<?,?it/s]

119


  0%|          |0/100[00:00<?,?it/s]

120


  0%|          |0/100[00:00<?,?it/s]

121


  0%|          |0/100[00:00<?,?it/s]

122


  0%|          |0/100[00:00<?,?it/s]

123


  0%|          |0/100[00:00<?,?it/s]

124


  0%|          |0/100[00:00<?,?it/s]

125


  0%|          |0/100[00:00<?,?it/s]

126


  0%|          |0/100[00:00<?,?it/s]

127


  0%|          |0/100[00:00<?,?it/s]

128


  0%|          |0/100[00:00<?,?it/s]

129


  0%|          |0/100[00:00<?,?it/s]

130


  0%|          |0/100[00:00<?,?it/s]

131


  0%|          |0/100[00:00<?,?it/s]

132


  0%|          |0/100[00:00<?,?it/s]

133
134
135


  0%|          |0/100[00:00<?,?it/s]

136


  0%|          |0/100[00:00<?,?it/s]

137


  0%|          |0/100[00:00<?,?it/s]

138


  0%|          |0/100[00:00<?,?it/s]

139


  0%|          |0/100[00:00<?,?it/s]

140


  0%|          |0/100[00:00<?,?it/s]

141


  0%|          |0/100[00:00<?,?it/s]

142


  0%|          |0/100[00:00<?,?it/s]

143


  0%|          |0/100[00:00<?,?it/s]

144


  0%|          |0/100[00:00<?,?it/s]

145


  0%|          |0/100[00:00<?,?it/s]

146


  0%|          |0/100[00:00<?,?it/s]

147


  0%|          |0/100[00:00<?,?it/s]

148


  0%|          |0/100[00:00<?,?it/s]

149


  0%|          |0/100[00:00<?,?it/s]

150


  0%|          |0/100[00:00<?,?it/s]

151
152


  0%|          |0/100[00:00<?,?it/s]

153


  0%|          |0/100[00:00<?,?it/s]

154
155


  0%|          |0/100[00:00<?,?it/s]

156


  0%|          |0/100[00:00<?,?it/s]

157


  0%|          |0/100[00:00<?,?it/s]

158
159


  0%|          |0/100[00:00<?,?it/s]

160


  0%|          |0/100[00:00<?,?it/s]

161


  0%|          |0/100[00:00<?,?it/s]

162
163


  0%|          |0/100[00:00<?,?it/s]

164


  0%|          |0/100[00:00<?,?it/s]

165


  0%|          |0/100[00:00<?,?it/s]

166
167


  0%|          |0/100[00:00<?,?it/s]

168


  0%|          |0/100[00:00<?,?it/s]

169


  0%|          |0/100[00:00<?,?it/s]

170


  0%|          |0/100[00:00<?,?it/s]

171


  0%|          |0/100[00:00<?,?it/s]

172


  0%|          |0/100[00:00<?,?it/s]

173


  0%|          |0/100[00:00<?,?it/s]

174
175


  0%|          |0/100[00:00<?,?it/s]

176


  0%|          |0/100[00:00<?,?it/s]

177


  0%|          |0/100[00:00<?,?it/s]

178


  0%|          |0/100[00:00<?,?it/s]

179


  0%|          |0/100[00:00<?,?it/s]

180


  0%|          |0/100[00:00<?,?it/s]

181


  0%|          |0/100[00:00<?,?it/s]

182


  0%|          |0/100[00:00<?,?it/s]

183
184


  0%|          |0/100[00:00<?,?it/s]

185


  0%|          |0/100[00:00<?,?it/s]

186


  0%|          |0/100[00:00<?,?it/s]

187


  0%|          |0/100[00:00<?,?it/s]

188


  0%|          |0/100[00:00<?,?it/s]

189
190


  0%|          |0/100[00:00<?,?it/s]

191


  0%|          |0/100[00:00<?,?it/s]

192


  0%|          |0/100[00:00<?,?it/s]

193


  0%|          |0/100[00:00<?,?it/s]

194


  0%|          |0/100[00:00<?,?it/s]

195


  0%|          |0/100[00:00<?,?it/s]

196


  0%|          |0/100[00:00<?,?it/s]

197


  0%|          |0/100[00:00<?,?it/s]

198


  0%|          |0/100[00:00<?,?it/s]

199
200
201


  0%|          |0/100[00:00<?,?it/s]

202


  0%|          |0/100[00:00<?,?it/s]

203


  0%|          |0/100[00:00<?,?it/s]

204


  0%|          |0/100[00:00<?,?it/s]

205
206
207


  0%|          |0/100[00:00<?,?it/s]

208


  0%|          |0/100[00:00<?,?it/s]

209
210


  0%|          |0/100[00:00<?,?it/s]

211


  0%|          |0/100[00:00<?,?it/s]

212


  0%|          |0/100[00:00<?,?it/s]

213


  0%|          |0/100[00:00<?,?it/s]

In [ ]:
print("Samples needed: {}".format(needed_1))
synth_1 = sample_needed_label(needed_1, '1')

In [ ]:
print("Samples needed: {}".format(needed_2))
synth_2 = sample_needed_label(needed_2, '2')

In [ ]:
# df_synth = pd.concat([synth_0, synth_minus1, synth_minus2, synth_1, synth_2], ignore_index=True)
df_synth = pd.concat([synth_minus1, synth_minus2, synth_1, synth_2], ignore_index=True)
df_synth['Discrete Thermal Comfort_TA'] = pd.to_numeric(df_synth['Discrete Thermal Comfort_TA'])
print(df_synth['Discrete Thermal Comfort_TA'].value_counts())
df_synth_train_balanced = pd.concat([df_synth, df_feature1_train], ignore_index=True)
print(df_synth_train_balanced['Discrete Thermal Comfort_TA'].value_counts())
print(df_synth_train_balanced)

# approximate to 2 decimal points, as original dataset
df_synth_train_balanced = df_synth_train_balanced.round(2)

print(df_synth_train_balanced)

## Train: train set + synth

In [ ]:
# load best models NB, KNN, SVM, MLP
acc_nb_synth_train_balanced, nb_optimal_synth_train_balanced = buildTrainNB(df_synth_train_balanced, test_size_percentage=test_size_percentage)
acc_knn_synth_train_balanced, knn_optimal_synth_train_balanced = buildTrainKNN(df_synth_train_balanced, test_size_percentage=test_size_percentage)
acc_svm_synth_train_balanced, svm_optimal_synth_train_balanced = buildTrainSVM(df_synth_train_balanced, test_size_percentage=test_size_percentage)

# using the optimal model. re-train in whole train split and test in unseen test split
acc_nb_synth_train_balanced_corr, _ = trainTest_tunedModel(df_feature1_test, nb_optimal_synth_train_balanced)
acc_knn_synth_train_balanced_corr, _ = trainTest_tunedModel(df_feature1_test, knn_optimal_synth_train_balanced)
acc_svm_synth_train_balanced_corr, _ = trainTest_tunedModel(df_feature1_test, svm_optimal_synth_train_balanced)

print("original train")
print(acc_holistic_knn_1)
print(acc_holistic_nb_1)
print(acc_holistic_svm_1)
print("\n")

print("more balanced train")
print(acc_nb_synth_train_balanced_corr)
print(acc_knn_synth_train_balanced_corr)
print(acc_svm_synth_train_balanced_corr)


In [ ]:
"""
original train
0.5885509838998211
0.5974955277280859
0.5974955277280859

# same size synth
more balanced train
0.5974955277280859
0.42397137745974955
0.26654740608228983

# twice synth
0.5974955277280859
0.4525939177101968
0.007155635062611807

# three times synth
0.5974955277280859
0.4203935599284436
0.08050089445438283

"""

## Train: synth

In [ ]:
df_synth = pd.concat([synth_0, synth_minus1, synth_minus2, synth_1, synth_2], ignore_index=True)
df_synth['Discrete Thermal Comfort_TA'] = pd.to_numeric(df_synth['Discrete Thermal Comfort_TA'])
print(df_synth['Discrete Thermal Comfort_TA'].value_counts())
df_synth = df_synth.round(2)

print(df_synth)

# load best models NB, KNN, SVM, MLP
acc_nb_synth, nb_optimal_synth = buildTrainNB(df_synth, test_size_percentage=test_size_percentage)
acc_knn_synth, knn_optimal_synth = buildTrainKNN(df_synth, test_size_percentage=test_size_percentage)
acc_svm_synth, svm_optimal_synth = buildTrainSVM(df_synth, test_size_percentage=test_size_percentage)

# using the optimal model. re-train in whole train split and test in unseen test split
acc_nb_synth, _ = trainTest_tunedModel(df_feature1_test, nb_optimal_synth)
acc_knn_synth, _ = trainTest_tunedModel(df_feature1_test, knn_optimal_synth)
acc_svm_synth, _ = trainTest_tunedModel(df_feature1_test, svm_optimal_synth)

print("original train")
print(acc_holistic_knn_1)
print(acc_holistic_nb_1)
print(acc_holistic_svm_1)
print("\n")

print("more balanced train")
print(acc_nb_synth)
print(acc_knn_synth)
print(acc_svm_synth)

In [ ]:
"""
original train
0.5885509838998211
0.5974955277280859
0.5974955277280859

# same size synth # CHANGE
0.5974955277280859
0.5116279069767442
0.5974955277280859

# twice synth # CHANGE
0.007155635062611807
0.2772808586762075
0.007155635062611807

# three times synth
0.007155635062611807
0.3023255813953488
0.007155635062611807

"""


In [ ]:
all_datasets = pd.DataFrame([
                            # train
                            ['KNN', 'Train', 0.59],
                            ['SVM', 'Train', 0.60],
                            ['NB', 'Train', 0.60],
                            
                            # train + synth1 
                            ['KNN', 'Train+Synth1-TGAN', 0.6],
                            ['SVM', 'Train+Synth1-TGAN', 0.42],
                            ['NB', 'Train+Synth1-TGAN', 0.27],

                            ['KNN', 'Train+Synth1-GANCorr', 0.49],
                            ['SVM', 'Train+Synth1-GANCorr', 0.45],
                            ['NB', 'Train+Synth1-GANCorr', 0.60],

                            ['KNN', 'Train+Synth1-GAN', 0.08],
                            ['SVM', 'Train+Synth1-GAN', 0.49],
                            ['NB', 'Train+Synth1-GAN', 0.60],
    
                            # synth1
                            ['KNN', 'Synth1-TGAN', 0.60],
                            ['SVM', 'Synth1-TGAN', 0.51],
                            ['NB', 'Synth1-TGAN', 0.60],
                            
                            ['KNN', 'Synth1-GANCorr', 0.02],
                            ['SVM', 'Synth1-GANCorr', 0.61],
                            ['NB', 'Synth1-GANCorr', 0.60],
    
                            ['KNN', 'Synth1-GAN', 0.08],
                            ['SVM', 'Synth1-GAN', 0.63],
                            ['NB', 'Synth1-GAN', 0.60],
    
                            # train + synth2
                            ['KNN', 'Train+Synth2-TGAN', 0.6],
                            ['SVM', 'Train+Synth2-TGAN', 0.45],
                            ['NB', 'Train+Synth2-TGAN', 0.01],
                            
                            ['KNN', 'Train+Synth2-GANCorr', 0.49],
                            ['SVM', 'Train+Synth2-GANCorr', 0.42],
                            ['NB', 'Train+Synth2-GANCorr', 0.6],
    
                            ['KNN', 'Train+Synth2-GAN', 0.08],
                            ['SVM', 'Train+Synth2-GAN', 0.42],
                            ['NB', 'Train+Synth2-GAN', 0.08],
    
                            # synth2
                            ['KNN', 'Synth2-TGAN', 0.01],
                            ['SVM', 'Synth2-TGAN', 0.28],
                            ['NB', 'Synth2-TGAN', 0.01],                                                
                            
                            ['KNN', 'Synth2-GANCorr', 0.64],
                            ['SVM', 'Synth2-GANCorr', 0.48],
                            ['NB', 'Synth2-GANCorr', 0.60],  
                            
                            ['KNN', 'Synth2-GAN', 0.08],
                            ['SVM', 'Synth2-GAN', 0.57],
                            ['NB', 'Synth2-GAN', 0.60],  
    
                            # train + synth3
                            ['KNN', 'Train+Synth3-TGAN', 0.60],
                            ['SVM', 'Train+Synth3-TGAN', 0.42],
                            ['NB', 'Train+Synth3-TGAN', 0.08],

                            ['KNN', 'Train+Synth3-GANCorr', 0.28],
                            ['SVM', 'Train+Synth3-GANCorr', 0.37],
                            ['NB', 'Train+Synth3-GANCorr', 0.6],
    
                            ['KNN', 'Train+Synth3-GAN', 0.08],
                            ['SVM', 'Train+Synth3-GAN', 0.46],
                            ['NB', 'Train+Synth3-GAN', 0.08],
    
                            # synth3
                            ['KNN', 'Synth3-TGAN', 0.01],
                            ['SVM', 'Synth3-TGAN', 0.30],
                            ['NB', 'Synth3-TGAN', 0.01],
    
                            ['KNN', 'Synth3-GANCorr', 0.24],
                            ['SVM', 'Synth3-GANCorr', 0.4],
                            ['NB', 'Synth3-GANCorr', 0.27],  
    
                            ['KNN', 'Synth3-GAN', 0.08],
                            ['SVM', 'Synth3-GAN', 0.51],
                            ['NB', 'Synth3-GAN', 0.08] 

                            ], columns = ['Model', 'Training Set and GAN', 'Accuracy'])

# plot heatmap
print("Metric: F1-score micro")
print("Data Split: 20% Test, 70% Train")
all_datasets = all_datasets.pivot("Training Set and GAN", "Model", "Accuracy")
fig = plt.figure(figsize=(12, 10))
sns.set(font_scale=1.5)
ax = sns.heatmap(all_datasets, linewidths = 0.5, annot = True, vmax = 1, cmap = "YlGnBu")
plt.tight_layout()
plt.show()